// packages/adapters/base/src/index.ts
export * from './wiring/host-wiring';
export * from './wiring/caps-builder';
export * from './gate/event-gate';
export * from './lifecycle/teardown';
export * from './host/adapter-host';
export * from './host/exposes';
export * from './host/view-epoch-owner';
export * from './host/view-visibility';
export * from './host/surface-projection';
export * from './events/web-event-router';
export * from './events/web-default-action';
export * from './gestures/web-move-gesture-host';
export * from './platform/instance-tree';
export * from './platform/layout-ready';
export * from './platform/web-preferences';
export * from './public-types';
export * from './types';
export * from './platform/focus-entry';
