import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import ts from 'typescript';

const DEFAULT_THEME_NAME = 'shadcn';
const DEFAULT_THEME_IMPORT = './shadcn-theme.css';
const DEFAULT_TOKENS_IMPORT = './prototype-tokens.generated.css';

const SHADCN_TOKENS_CSS = `/* This file is auto-generated by apps/www/scripts/generate-prototype-tailwind-sources.mjs. */
/* Do not edit by hand. */

@source inline("absolute");
@source inline("active:bg-background");
@source inline("active:bg-muted");
@source inline("active:bg-muted/80");
@source inline("active:scale-[0.98]");
@source inline("active:scale-[0.99]");
@source inline("active:shadow-xs");
@source inline("active:text-foreground");
@source inline("active:translate-y-px");
@source inline("aria-checked:bg-accent");
@source inline("aria-checked:bg-muted");
@source inline("aria-checked:bg-primary");
@source inline("aria-checked:pl-[22px]");
@source inline("aria-checked:pr-0.5");
@source inline("aria-checked:text-accent-foreground");
@source inline("aria-checked:text-muted-foreground");
@source inline("aria-checked:text-primary-foreground");
@source inline("aria-current:hidden");
@source inline("aria-expanded:bg-muted");
@source inline("aria-expanded:bg-secondary");
@source inline("aria-expanded:text-foreground");
@source inline("aria-expanded:text-secondary-foreground");
@source inline("aria-invalid:border-destructive");
@source inline("aria-invalid:ring-3");
@source inline("aria-invalid:ring-destructive/20");
@source inline("aria-selected:bg-background");
@source inline("aria-selected:shadow-xs");
@source inline("aria-selected:text-foreground");
@source inline("backdrop-blur-xs");
@source inline("bg-accent");
@source inline("bg-background");
@source inline("bg-background/70");
@source inline("bg-clip-padding");
@source inline("bg-destructive/10");
@source inline("bg-destructive/20");
@source inline("bg-destructive/30");
@source inline("bg-input");
@source inline("bg-input/30");
@source inline("bg-input/50");
@source inline("bg-input/80");
@source inline("bg-muted");
@source inline("bg-muted/60");
@source inline("bg-muted/80");
@source inline("bg-primary");
@source inline("bg-primary/80");
@source inline("bg-primary/90");
@source inline("bg-secondary");
@source inline("bg-secondary/80");
@source inline("bg-transparent");
@source inline("block");
@source inline("border");
@source inline("border-border");
@source inline("border-border/50");
@source inline("border-border/60");
@source inline("border-destructive");
@source inline("border-destructive/40");
@source inline("border-destructive/50");
@source inline("border-input");
@source inline("border-ring");
@source inline("border-transparent");
@source inline("cursor-default");
@source inline("dark:aria-checked:bg-input/50");
@source inline("dark:aria-checked:bg-primary");
@source inline("dark:aria-invalid:border-destructive/50");
@source inline("dark:aria-invalid:ring-destructive/40");
@source inline("dark:bg-destructive/20");
@source inline("dark:bg-input/30");
@source inline("dark:border-input");
@source inline("dark:data-[focus-visible]:ring-destructive/40");
@source inline("dark:hover:bg-destructive/30");
@source inline("dark:hover:bg-input/50");
@source inline("data-[disabled]:opacity-50");
@source inline("data-[disabled]:pointer-events-none");
@source inline("data-[focus-visible]:bg-background");
@source inline("data-[focus-visible]:border-destructive/40");
@source inline("data-[focus-visible]:border-ring");
@source inline("data-[focus-visible]:ring-2");
@source inline("data-[focus-visible]:ring-3");
@source inline("data-[focus-visible]:ring-destructive/20");
@source inline("data-[focus-visible]:ring-inset");
@source inline("data-[focus-visible]:ring-offset-2");
@source inline("data-[focus-visible]:ring-offset-background");
@source inline("data-[focus-visible]:ring-ring/40");
@source inline("data-[focus-visible]:ring-ring/50");
@source inline("data-[focus-visible]:shadow-xs");
@source inline("data-[focus-visible]:text-foreground");
@source inline("duration-200");
@source inline("ease-in-out");
@source inline("flex");
@source inline("flex-col");
@source inline("font-medium");
@source inline("gap-1");
@source inline("gap-1.5");
@source inline("gap-2");
@source inline("gap-3");
@source inline("group/button");
@source inline("h-10");
@source inline("h-6");
@source inline("h-7");
@source inline("h-8");
@source inline("h-9");
@source inline("hidden");
@source inline("hover:aria-checked:bg-input");
@source inline("hover:aria-checked:bg-muted/60");
@source inline("hover:aria-checked:bg-primary/90");
@source inline("hover:aria-checked:text-foreground");
@source inline("hover:aria-selected:bg-background/70");
@source inline("hover:aria-selected:shadow-xs");
@source inline("hover:aria-selected:text-foreground");
@source inline("hover:bg-destructive/20");
@source inline("hover:bg-muted");
@source inline("hover:bg-primary/80");
@source inline("hover:bg-secondary/80");
@source inline("hover:data-[focus-visible]:data-[focused]:bg-muted");
@source inline("hover:data-[focus-visible]:data-[focused]:text-foreground");
@source inline("hover:text-foreground");
@source inline("hover:underline");
@source inline("inline-flex");
@source inline("items-center");
@source inline("items-start");
@source inline("justify-center");
@source inline("leading-6");
@source inline("left-0");
@source inline("min-h-28");
@source inline("min-w-10");
@source inline("min-w-56");
@source inline("min-w-8");
@source inline("min-w-9");
@source inline("mt-2");
@source inline("opacity-50");
@source inline("outline-none");
@source inline("overflow-hidden");
@source inline("p-1");
@source inline("p-4");
@source inline("peer");
@source inline("pl-0.5");
@source inline("pl-[22px]");
@source inline("pointer-events-none");
@source inline("pr-0.5");
@source inline("pr-[22px]");
@source inline("px-2.5");
@source inline("px-3");
@source inline("px-5");
@source inline("py-1.5");
@source inline("py-2");
@source inline("relative");
@source inline("ring-0");
@source inline("ring-2");
@source inline("ring-3");
@source inline("ring-destructive/20");
@source inline("ring-destructive/40");
@source inline("ring-inset");
@source inline("ring-offset-2");
@source inline("ring-offset-background");
@source inline("ring-ring/40");
@source inline("ring-ring/50");
@source inline("rounded-[min(var(--radius-md),12px)]");
@source inline("rounded-full");
@source inline("rounded-lg");
@source inline("rounded-md");
@source inline("rounded-xl");
@source inline("scale-[0.98]");
@source inline("scale-[0.99]");
@source inline("select-none");
@source inline("shadow-lg");
@source inline("shadow-xs");
@source inline("shrink-0");
@source inline("size-5");
@source inline("size-8");
@source inline("text-[0.8rem]");
@source inline("text-accent-foreground");
@source inline("text-destructive");
@source inline("text-foreground");
@source inline("text-left");
@source inline("text-muted-foreground");
@source inline("text-primary");
@source inline("text-primary-foreground");
@source inline("text-secondary-foreground");
@source inline("text-sm");
@source inline("top-full");
@source inline("transition-all");
@source inline("transition-colors");
@source inline("translate-x-0");
@source inline("translate-y-px");
@source inline("underline");
@source inline("underline-offset-4");
@source inline("w-11");
@source inline("w-80");
@source inline("w-full");
@source inline("whitespace-nowrap");
@source inline("will-change-transform");
@source inline("z-50");
`;

const SHADCN_THEME_CSS = `:root {
  --radius: 0.625rem;
  --background: lab(100% 0 0);
  --foreground: lab(2.75381% 0 0);
  --card: lab(100% 0 0);
  --card-foreground: lab(2.75381% 0 0);
  --popover: lab(100% 0 0);
  --popover-foreground: lab(2.75381% 0 0);
  --primary: lab(7.78201% -0.0000149012 0);
  --primary-foreground: lab(98.26% 0 0);
  --secondary: lab(96.52% -0.0000298023 0.0000119209);
  --secondary-foreground: lab(7.78201% -0.0000149012 0);
  --muted: lab(96.52% -0.0000298023 0.0000119209);
  --muted-foreground: lab(48.496% 0 0);
  --accent: lab(96.52% -0.0000298023 0.0000119209);
  --accent-foreground: lab(7.78201% -0.0000149012 0);
  --destructive: lab(48.4493% 77.4328 61.5452);
  --destructive-foreground: lab(96.4152% 3.22586 1.14673);
  --border: lab(90.952% 0 -0.0000119209);
  --input: lab(90.952% 0 -0.0000119209);
  --ring: lab(66.128% -0.0000298023 0.0000119209);
  --chart-1: var(--color-blue-300);
  --chart-2: var(--color-blue-500);
  --chart-3: var(--color-blue-600);
  --chart-4: var(--color-blue-700);
  --chart-5: var(--color-blue-800);
  --sidebar: lab(98.26% 0 0);
  --sidebar-foreground: lab(2.75381% 0 0);
  --sidebar-primary: lab(7.78201% -0.0000149012 0);
  --sidebar-primary-foreground: lab(98.26% 0 0);
  --sidebar-accent: lab(96.52% -0.0000298023 0.0000119209);
  --sidebar-accent-foreground: lab(7.78201% -0.0000149012 0);
  --sidebar-border: lab(90.952% 0 -0.0000119209);
  --sidebar-ring: lab(66.128% -0.0000298023 0.0000119209);
  --surface: lab(97.68% -0.0000298023 0.0000119209);
  --surface-foreground: var(--foreground);
  --code: var(--surface);
  --code-foreground: var(--surface-foreground);
  --code-highlight: lab(95.36% 0 0);
  --code-number: lab(48.96% 0 0);
  --selection: lab(2.75381% 0 0);
  --selection-foreground: lab(100% 0 0);
}

:root.dark,
:root[data-theme='dark'] {
  --background: lab(2.75381% 0 0);
  --foreground: lab(98.26% 0 0);
  --card: lab(7.78201% -0.0000149012 0);
  --card-foreground: lab(98.26% 0 0);
  --popover: lab(7.78201% -0.0000149012 0);
  --popover-foreground: lab(98.26% 0 0);
  --primary: lab(90.952% 0 -0.0000119209);
  --primary-foreground: lab(7.78201% -0.0000149012 0);
  --secondary: lab(15.204% 0 -0.00000596046);
  --secondary-foreground: lab(98.26% 0 0);
  --muted: lab(15.204% 0 -0.00000596046);
  --muted-foreground: lab(66.128% -0.0000298023 0.0000119209);
  --accent: lab(27.036% 0 0);
  --accent-foreground: lab(98.26% 0 0);
  --destructive: lab(63.7053% 60.745 31.3109);
  --destructive-foreground: lab(49.0747% 69.3434 49.6251);
  --border: lab(100% 0 0 / 0.1);
  --input: lab(100% 0 0 / 0.15);
  --ring: lab(48.496% 0 0);
  --chart-1: var(--color-blue-300);
  --chart-2: var(--color-blue-500);
  --chart-3: var(--color-blue-600);
  --chart-4: var(--color-blue-700);
  --chart-5: var(--color-blue-800);
  --sidebar: lab(7.78201% -0.0000149012 0);
  --sidebar-foreground: lab(98.26% 0 0);
  --sidebar-primary: lab(36.9089% 35.0961 -85.6872);
  --sidebar-primary-foreground: lab(98.26% 0 0);
  --sidebar-accent: lab(15.204% 0 -0.00000596046);
  --sidebar-accent-foreground: lab(98.26% 0 0);
  --sidebar-border: lab(100% 0 0 / 0.1);
  --sidebar-ring: lab(34.924% 0 0);
  --surface: lab(7.22637% -0.0000149012 0);
  --surface-foreground: lab(66.128% -0.0000298023 0.0000119209);
  --code: var(--surface);
  --code-foreground: var(--surface-foreground);
  --code-highlight: lab(15.32% 0 0);
  --code-number: lab(67.52% -0.0000298023 0);
  --selection: lab(90.952% 0 -0.0000119209);
  --selection-foreground: lab(7.78201% -0.0000149012 0);
}
`;

const TAILWIND_BASE_TEMPLATE = `@import 'tailwindcss';
@import '__THEME_IMPORT__';
@import '__TOKENS_IMPORT__';

@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));

@theme {
  --radius: 0.625rem;
  --radius-xl: calc(var(--radius) + 4px);
  --radius-lg: var(--radius);
  --radius-md: calc(var(--radius) - 2px);
  --radius-sm: calc(var(--radius) - 4px);
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
  --color-surface: var(--surface);
  --color-surface-foreground: var(--surface-foreground);
  --color-code: var(--code);
  --color-code-foreground: var(--code-foreground);
  --color-code-highlight: var(--code-highlight);
  --color-code-number: var(--code-number);
  --color-selection: var(--selection);
  --color-selection-foreground: var(--selection-foreground);
}

@font-face {
  font-family: 'GeistSans';
  src: url('./assets/font/GeistVF.woff2') format('woff2-variations');
}

@layer base {
  :root {
    --radius-xl: calc(var(--radius) + 4px);
    --radius-lg: var(--radius);
    --radius-md: calc(var(--radius) - 2px);
    --radius-sm: calc(var(--radius) - 4px);
  }

  * {
    border-color: var(--color-border);
  }
}

body {
  background-color: var(--color-background);
  color: var(--color-foreground);
  font-family:
    var(--color-font-geist-sans),
    ui-sans-serif,
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    'Segoe UI',
    Roboto,
    'Helvetica Neue',
    Arial,
    'Noto Sans',
    sans-serif,
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'Noto Color Emoji';
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  unicode-bidi: isolate;
  font-feature-settings: normal;
  font-synthesis-weight: none;
  font-variation-settings: normal;
  text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}
`;

export async function run(argv) {
  const [command, ...rest] = argv;

  if (!command || command === '--help' || command === '-h') {
    printHelp();
    return;
  }

  if (command === 'tokens') {
    await runGenerateTokens(rest);
    return;
  }

  if (command === 'tailwindcss') {
    await runGenerateTailwindCss(rest);
    return;
  }

  if (command === 'theme') {
    await runGenerateTheme(rest);
    return;
  }

  await runPreset(command, rest);
}

function printHelp() {
  console.log(`proto-ui

Usage:
  proto-ui <theme> [--styles-dir <dir>]
  proto-ui tokens --input <dir> --out <file>
  proto-ui tailwindcss [--theme-import <path>] [--tokens-import <path>] --out <file>
  proto-ui theme <name> --out <file>

Examples:
  proto-ui shadcn --styles-dir ./src/styles
  proto-ui tokens --input ./packages/prototypes --out ./src/styles/prototype-tokens.generated.css
  proto-ui tailwindcss --out ./src/styles/tailwindcss.css
  proto-ui theme shadcn --out ./src/styles/shadcn-theme.css
`);
}

async function runPreset(themeName, args) {
  const options = parseOptions(args);
  const normalizedTheme = themeName.toLowerCase();
  if (normalizedTheme !== DEFAULT_THEME_NAME) {
    throw new Error(
      `unsupported theme "${themeName}". currently supported: ${DEFAULT_THEME_NAME}.`
    );
  }
  const stylesDir = options['styles-dir'] ?? './src/styles';
  const tokensFileName = options['tokens-file'] ?? 'prototype-tokens.generated.css';
  const tailwindFileName = options['tailwind-file'] ?? 'tailwindcss.css';
  const themeFileName = options['theme-file'] ?? `${normalizedTheme}-theme.css`;

  const tokensOut = path.join(stylesDir, tokensFileName);
  const themeOut = path.join(stylesDir, themeFileName);
  const tailwindOut = path.join(stylesDir, tailwindFileName);

  const tokensOutputFile = path.resolve(process.cwd(), tokensOut);
  await ensureDirectory(tokensOutputFile);
  await fs.writeFile(tokensOutputFile, SHADCN_TOKENS_CSS, 'utf8');
  console.log(`[proto-ui] tokens(preset): wrote ${relativeToCwd(tokensOutputFile)}`);

  await runGenerateTheme([normalizedTheme, '--out', themeOut]);

  const tailwindAbs = path.resolve(process.cwd(), tailwindOut);
  const themeImport = toCssImportPath(tailwindAbs, path.resolve(process.cwd(), themeOut));
  const tokensImport = toCssImportPath(tailwindAbs, path.resolve(process.cwd(), tokensOut));

  await runGenerateTailwindCss([
    '--out',
    tailwindOut,
    '--theme-import',
    themeImport,
    '--tokens-import',
    tokensImport,
  ]);

  console.log(
    `[proto-ui] setup(${normalizedTheme}): completed tokens + theme + tailwindcss in ${stylesDir}`
  );
}

async function runGenerateTokens(args) {
  const options = parseOptions(args);
  const input = requiredOption(options, 'input');
  const outFile = requiredOption(options, 'out');
  const root = path.resolve(process.cwd(), input);
  const outputFile = path.resolve(process.cwd(), outFile);

  const files = await collectSourceFiles(root);
  const tokens = new Set();

  for (const file of files) {
    const sourceText = await fs.readFile(file, 'utf8');
    const sourceFile = ts.createSourceFile(
      file,
      sourceText,
      ts.ScriptTarget.Latest,
      true,
      scriptKindForFile(file)
    );
    const scope = createScope();
    walk(sourceFile, scope, tokens);
  }

  const css = renderTokenCss(Array.from(tokens).sort());
  await ensureDirectory(outputFile);
  await fs.writeFile(outputFile, css, 'utf8');
  console.log(`[proto-ui] tokens: wrote ${tokens.size} tokens -> ${relativeToCwd(outputFile)}`);
}

async function runGenerateTailwindCss(args) {
  const options = parseOptions(args);
  const outFile = requiredOption(options, 'out');
  const themeImport = options['theme-import'] ?? DEFAULT_THEME_IMPORT;
  const tokensImport = options['tokens-import'] ?? DEFAULT_TOKENS_IMPORT;
  const outputFile = path.resolve(process.cwd(), outFile);
  const css = TAILWIND_BASE_TEMPLATE.replace('__THEME_IMPORT__', themeImport).replace(
    '__TOKENS_IMPORT__',
    tokensImport
  );

  await ensureDirectory(outputFile);
  await fs.writeFile(outputFile, css, 'utf8');
  console.log(`[proto-ui] tailwindcss: wrote ${relativeToCwd(outputFile)}`);
}

async function runGenerateTheme(args) {
  const [name, ...rest] = args;
  if (!name || name.startsWith('-')) {
    throw new Error(
      'theme name is required. Example: proto-ui theme shadcn --out ./src/styles/shadcn-theme.css'
    );
  }

  const options = parseOptions(rest);
  const outFile = requiredOption(options, 'out');
  const outputFile = path.resolve(process.cwd(), outFile);
  const normalizedName = name.toLowerCase();

  let css = '';
  if (normalizedName === DEFAULT_THEME_NAME) {
    css = SHADCN_THEME_CSS;
  } else {
    throw new Error(`unsupported theme "${name}". currently supported: ${DEFAULT_THEME_NAME}.`);
  }

  await ensureDirectory(outputFile);
  await fs.writeFile(outputFile, css, 'utf8');
  console.log(`[proto-ui] theme(${normalizedName}): wrote ${relativeToCwd(outputFile)}`);
}

function parseOptions(args) {
  const options = {};
  for (let i = 0; i < args.length; i += 1) {
    const token = args[i];
    if (!token.startsWith('--')) continue;
    const key = token.slice(2);
    const next = args[i + 1];
    if (!next || next.startsWith('--')) {
      options[key] = 'true';
      continue;
    }
    options[key] = next;
    i += 1;
  }
  return options;
}

function requiredOption(options, key) {
  const value = options[key];
  if (!value) throw new Error(`missing required option: --${key}`);
  return value;
}

async function ensureDirectory(filePath) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
}

function relativeToCwd(filePath) {
  return path.relative(process.cwd(), filePath) || '.';
}

function toCssImportPath(fromFile, toFile) {
  const fromDir = path.dirname(fromFile);
  const relative = path.relative(fromDir, toFile).replace(/\\/g, '/');
  if (relative.startsWith('.')) return relative;
  return `./${relative}`;
}

function createScope(parent = null) {
  return { parent, bindings: new Map() };
}

function walk(node, scope, tokens) {
  if (createsScope(node)) {
    const nextScope = createScope(scope);

    if (hasStatements(node)) {
      for (const stmt of node.statements) {
        if (ts.isVariableStatement(stmt)) {
          for (const decl of stmt.declarationList.declarations) {
            registerDeclaration(decl, nextScope);
            if (decl.initializer) walk(decl.initializer, nextScope, tokens);
          }
          continue;
        }
        walk(stmt, nextScope, tokens);
      }
      return;
    }

    ts.forEachChild(node, (child) => walk(child, nextScope, tokens));
    return;
  }

  if (
    ts.isCallExpression(node) &&
    ts.isIdentifier(node.expression) &&
    node.expression.text === 'tw'
  ) {
    for (const arg of node.arguments) {
      const value = resolveExpression(arg, scope);
      for (const token of value.strings.flatMap(splitTokens)) {
        tokens.add(token);
      }
    }
  }

  if (ts.isCallExpression(node) && isPropertyNamed(node.expression, 'rule')) {
    collectRuleVariantTokens(node, scope, tokens);
  }

  ts.forEachChild(node, (child) => walk(child, scope, tokens));
}

function createsScope(node) {
  return (
    ts.isSourceFile(node) ||
    ts.isBlock(node) ||
    ts.isModuleBlock(node) ||
    ts.isCaseBlock(node) ||
    ts.isFunctionDeclaration(node) ||
    ts.isFunctionExpression(node) ||
    ts.isArrowFunction(node)
  );
}

function hasStatements(node) {
  return (
    ts.isSourceFile(node) || ts.isBlock(node) || ts.isModuleBlock(node) || ts.isCaseBlock(node)
  );
}

function registerDeclaration(decl, scope) {
  if (!ts.isIdentifier(decl.name) || !decl.initializer) return;
  scope.bindings.set(decl.name.text, resolveBinding(decl.initializer, scope));
}

function resolveExpression(node, scope) {
  if (ts.isStringLiteralLike(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return asStringValue([node.text]);
  }

  if (ts.isArrayLiteralExpression(node)) {
    const parts = [];
    for (const element of node.elements) {
      const value = resolveExpression(element, scope);
      if (!value.single) return emptyValue();
      parts.push(value.single);
    }
    return asStringValue([parts.join(',')]);
  }

  if (
    ts.isCallExpression(node) &&
    ts.isPropertyAccessExpression(node.expression) &&
    node.expression.name.text === 'join'
  ) {
    return resolveJoinCall(node, scope);
  }

  if (ts.isIdentifier(node)) {
    return lookup(node.text, scope);
  }

  if (
    ts.isParenthesizedExpression(node) ||
    ts.isAsExpression(node) ||
    ts.isTypeAssertionExpression(node)
  ) {
    return resolveExpression(node.expression, scope);
  }

  if (ts.isObjectLiteralExpression(node)) {
    const entries = new Map();
    for (const prop of node.properties) {
      if (ts.isPropertyAssignment(prop)) {
        const key = getPropertyName(prop.name);
        if (!key) continue;
        const value = resolveExpression(prop.initializer, scope);
        if (value.strings.length > 0) entries.set(key, value.strings);
      } else if (ts.isShorthandPropertyAssignment(prop)) {
        const value = lookup(prop.name.text, scope);
        if (value.strings.length > 0) entries.set(prop.name.text, value.strings);
      }
    }
    return asMapValue(entries);
  }

  if (ts.isElementAccessExpression(node)) {
    const base = resolveExpression(node.expression, scope);
    if (!base.map) return emptyValue();

    if (node.argumentExpression && ts.isStringLiteralLike(node.argumentExpression)) {
      return asStringValue(base.map.get(node.argumentExpression.text) ?? []);
    }

    const out = new Set();
    for (const strings of base.map.values()) {
      for (const value of strings) out.add(value);
    }
    return asStringValue(Array.from(out));
  }

  if (ts.isConditionalExpression(node)) {
    const values = new Set([
      ...resolveExpression(node.whenTrue, scope).strings,
      ...resolveExpression(node.whenFalse, scope).strings,
    ]);
    return asStringValue(Array.from(values));
  }

  return emptyValue();
}

function resolveJoinCall(node, scope) {
  const separatorArg = node.arguments[0];
  const separator =
    separatorArg &&
    (ts.isStringLiteralLike(separatorArg) || ts.isNoSubstitutionTemplateLiteral(separatorArg))
      ? separatorArg.text
      : ',';
  const base = resolveExpression(node.expression.expression, scope);
  if (!base.single) return emptyValue();
  return asStringValue([base.single.split(',').join(separator)]);
}

function lookup(name, scope) {
  let current = scope;
  while (current) {
    const value = current.bindings.get(name);
    if (value) return value;
    current = current.parent;
  }
  return emptyValue();
}

function resolveBinding(node, scope) {
  const semantic = resolveSemanticBinding(node);
  const value = resolveExpression(node, scope);
  return semantic ? { ...value, semantic } : value;
}

function resolveSemanticBinding(node) {
  if (
    !ts.isCallExpression(node) ||
    !isPropertyAccessChain(node.expression, ['state', 'fromInteraction'])
  ) {
    if (
      !ts.isCallExpression(node) ||
      !isPropertyAccessChain(node.expression, ['state', 'fromAccessibility'])
    ) {
      return null;
    }
  }

  const kind = node.expression.name.text === 'fromInteraction' ? 'interaction' : 'accessibility';
  const firstArg = node.arguments[0];
  if (!firstArg || !ts.isStringLiteralLike(firstArg)) return null;
  const name = firstArg.text;

  if (kind === 'interaction') {
    return (
      {
        hovered: 'hover',
        pressed: 'active',
        disabled: 'data-[disabled]',
        focused: 'data-[focused]',
        focusVisible: 'data-[focus-visible]',
      }[name] ?? null
    );
  }

  return (
    {
      expanded: 'aria-expanded',
      invalid: 'aria-invalid',
      selected: 'aria-selected',
      checked: 'aria-checked',
      current: 'aria-current',
    }[name] ?? null
  );
}

function collectRuleVariantTokens(node, scope, tokens) {
  const config = node.arguments[0];
  if (!config || !ts.isObjectLiteralExpression(config)) return;

  const whenProp = config.properties.find(
    (prop) => ts.isPropertyAssignment(prop) && getPropertyName(prop.name) === 'when'
  );
  const intentProp = config.properties.find(
    (prop) => ts.isPropertyAssignment(prop) && getPropertyName(prop.name) === 'intent'
  );
  if (
    !whenProp ||
    !intentProp ||
    !ts.isPropertyAssignment(whenProp) ||
    !ts.isPropertyAssignment(intentProp)
  ) {
    return;
  }

  const variants = analyzeWhenVariants(whenProp.initializer, scope);
  if (variants.length === 0) return;

  const intentTokens = collectTwTokens(intentProp.initializer, scope);
  for (const token of intentTokens) {
    tokens.add(`${variants.join(':')}:${token}`);
  }
}

function analyzeWhenVariants(node, scope) {
  const out = new Set();

  visit(node);
  return Array.from(out).sort(compareVariants);

  function visit(current) {
    if (ts.isArrowFunction(current) || ts.isFunctionExpression(current)) {
      visit(current.body);
      return;
    }

    if (
      ts.isParenthesizedExpression(current) ||
      ts.isAsExpression(current) ||
      ts.isTypeAssertionExpression(current)
    ) {
      visit(current.expression);
      return;
    }

    if (ts.isCallExpression(current) && ts.isPropertyAccessExpression(current.expression)) {
      const method = current.expression.name.text;

      if (method === 'all' || method === 'any') {
        for (const arg of current.arguments) visit(arg);
        return;
      }

      if (method === 'eq') {
        const subject = current.expression.expression;
        if (ts.isCallExpression(subject) && ts.isPropertyAccessExpression(subject.expression)) {
          const subjectMethod = subject.expression.name.text;
          if (subjectMethod === 'state') {
            const firstArg = subject.arguments[0];
            if (firstArg && ts.isIdentifier(firstArg)) {
              const binding = lookup(firstArg.text, scope);
              if (binding.semantic) out.add(binding.semantic);
            }
            return;
          }

          if (subjectMethod === 'meta') {
            const key = subject.arguments[0];
            const value = current.arguments[0];
            if (
              key &&
              value &&
              ts.isStringLiteralLike(key) &&
              ts.isStringLiteralLike(value) &&
              key.text === 'colorScheme' &&
              value.text === 'dark'
            ) {
              out.add('dark');
            }
          }
        }
      }
    }

    ts.forEachChild(current, visit);
  }
}

function collectTwTokens(node, scope) {
  const found = new Set();

  visit(node, scope);
  return Array.from(found);

  function visit(current, currentScope) {
    if (createsScope(current)) {
      const nextScope = createScope(currentScope);
      if (hasStatements(current)) {
        for (const stmt of current.statements) {
          if (ts.isVariableStatement(stmt)) {
            for (const decl of stmt.declarationList.declarations) {
              registerDeclaration(decl, nextScope);
              if (decl.initializer) visit(decl.initializer, nextScope);
            }
            continue;
          }
          visit(stmt, nextScope);
        }
        return;
      }
    }

    if (
      ts.isCallExpression(current) &&
      ts.isIdentifier(current.expression) &&
      current.expression.text === 'tw'
    ) {
      for (const arg of current.arguments) {
        const value = resolveExpression(arg, currentScope);
        for (const token of value.strings.flatMap(splitTokens)) found.add(token);
      }
    }

    ts.forEachChild(current, (child) => visit(child, currentScope));
  }
}

function compareVariants(a, b) {
  const order = ['dark', 'hover', 'active', 'focus', 'focus-visible', 'disabled'];
  const ai = order.indexOf(a);
  const bi = order.indexOf(b);
  if (ai !== -1 || bi !== -1) return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
  return a.localeCompare(b);
}

function isPropertyNamed(node, name) {
  return ts.isPropertyAccessExpression(node) && node.name.text === name;
}

function isPropertyAccessChain(node, names) {
  let current = node;
  for (let i = names.length - 1; i >= 0; i -= 1) {
    if (!ts.isPropertyAccessExpression(current) || current.name.text !== names[i]) return false;
    current = current.expression;
  }
  return ts.isIdentifier(current);
}

function getPropertyName(name) {
  if (ts.isIdentifier(name) || ts.isStringLiteralLike(name)) return name.text;
  return null;
}

function splitTokens(value) {
  return value
    .split(/\s+/)
    .map((token) => token.trim())
    .filter(Boolean);
}

function emptyValue() {
  return { strings: [], single: null, map: null, semantic: null };
}

function asStringValue(strings) {
  return {
    strings,
    single: strings.length === 1 ? strings[0] : null,
    map: null,
    semantic: null,
  };
}

function asMapValue(map) {
  const strings = [];
  for (const values of map.values()) strings.push(...values);
  return {
    strings,
    single: null,
    map,
    semantic: null,
  };
}

function renderTokenCss(tokens) {
  const lines = [
    '/* This file is auto-generated by @proto.ui/cli (proto-ui tokens). */',
    '/* Do not edit by hand. */',
    '',
  ];

  for (const token of tokens) {
    lines.push(`@source inline("${escapeForCss(token)}");`);
  }

  lines.push('');
  return lines.join('\n');
}

function escapeForCss(token) {
  return token.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function scriptKindForFile(file) {
  const ext = path.extname(file).toLowerCase();
  if (ext === '.tsx') return ts.ScriptKind.TSX;
  if (ext === '.jsx') return ts.ScriptKind.JSX;
  if (ext === '.js' || ext === '.mjs' || ext === '.cjs') return ts.ScriptKind.JS;
  return ts.ScriptKind.TS;
}

async function collectSourceFiles(dir) {
  const out = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'dist' || entry.name === 'test' || entry.name === 'node_modules') continue;
      out.push(...(await collectSourceFiles(fullPath)));
      continue;
    }
    if (
      entry.isFile() &&
      /\.(ts|tsx|mts|cts|js|jsx|mjs|cjs)$/.test(entry.name) &&
      !/\.d\.ts$/i.test(entry.name)
    ) {
      out.push(fullPath);
    }
  }
  return out;
}
