export const ADAPTER_PACKAGES = {
  vue: '@proto.ui/adapter-vue',
  react: '@proto.ui/adapter-react',
  'web-component': '@proto.ui/adapter-web-component',
  wc: '@proto.ui/adapter-web-component',
};

export const PROTOTYPE_PACKAGES = {
  shadcn: '@proto.ui/prototypes-shadcn',
};

export const CLI_PACKAGE = '@proto.ui/cli';

export const DEFAULT_THEME_NAME = 'shadcn';
export const DEFAULT_THEME_IMPORT = './shadcn-theme.css';
export const DEFAULT_TOKENS_IMPORT = './prototype-tokens.generated.css';

export const SHADCN_TOKENS_CSS = `/* This file is auto-generated by apps/www/scripts/generate-prototype-tailwind-sources.mjs. */
  /* Do not edit by hand. */
  
  @source inline("absolute");
  @source inline("active:bg-background");
  @source inline("active:bg-muted");
  @source inline("active:bg-muted/80");
  @source inline("active:scale-[0.98]");
  @source inline("active:scale-[0.99]");
  @source inline("active:shadow-xs");
  @source inline("active:text-foreground");
  @source inline("active:translate-y-px");
  @source inline("aria-checked:bg-accent");
  @source inline("aria-checked:bg-muted");
  @source inline("aria-checked:bg-primary");
  @source inline("aria-checked:pl-[22px]");
  @source inline("aria-checked:pr-0.5");
  @source inline("aria-checked:text-accent-foreground");
  @source inline("aria-checked:text-muted-foreground");
  @source inline("aria-checked:text-primary-foreground");
  @source inline("aria-current:hidden");
  @source inline("aria-expanded:bg-muted");
  @source inline("aria-expanded:bg-secondary");
  @source inline("aria-expanded:text-foreground");
  @source inline("aria-expanded:text-secondary-foreground");
  @source inline("aria-invalid:border-destructive");
  @source inline("aria-invalid:ring-3");
  @source inline("aria-invalid:ring-destructive/20");
  @source inline("aria-selected:bg-background");
  @source inline("aria-selected:shadow-xs");
  @source inline("aria-selected:text-foreground");
  @source inline("backdrop-blur-xs");
  @source inline("bg-accent");
  @source inline("bg-background");
  @source inline("bg-background/70");
  @source inline("bg-clip-padding");
  @source inline("bg-destructive/10");
  @source inline("bg-destructive/20");
  @source inline("bg-destructive/30");
  @source inline("bg-input");
  @source inline("bg-input/30");
  @source inline("bg-input/50");
  @source inline("bg-input/80");
  @source inline("bg-muted");
  @source inline("bg-muted/60");
  @source inline("bg-muted/80");
  @source inline("bg-primary");
  @source inline("bg-primary/80");
  @source inline("bg-primary/90");
  @source inline("bg-secondary");
  @source inline("bg-secondary/80");
  @source inline("bg-transparent");
  @source inline("block");
  @source inline("border");
  @source inline("border-border");
  @source inline("border-border/50");
  @source inline("border-border/60");
  @source inline("border-destructive");
  @source inline("border-destructive/40");
  @source inline("border-destructive/50");
  @source inline("border-input");
  @source inline("border-ring");
  @source inline("border-transparent");
  @source inline("cursor-default");
  @source inline("dark:aria-checked:bg-input/50");
  @source inline("dark:aria-checked:bg-primary");
  @source inline("dark:aria-invalid:border-destructive/50");
  @source inline("dark:aria-invalid:ring-destructive/40");
  @source inline("dark:bg-destructive/20");
  @source inline("dark:bg-input/30");
  @source inline("dark:border-input");
  @source inline("dark:data-[focus-visible]:ring-destructive/40");
  @source inline("dark:hover:bg-destructive/30");
  @source inline("dark:hover:bg-input/50");
  @source inline("data-[disabled]:opacity-50");
  @source inline("data-[disabled]:pointer-events-none");
  @source inline("data-[focus-visible]:bg-background");
  @source inline("data-[focus-visible]:border-destructive/40");
  @source inline("data-[focus-visible]:border-ring");
  @source inline("data-[focus-visible]:ring-2");
  @source inline("data-[focus-visible]:ring-3");
  @source inline("data-[focus-visible]:ring-destructive/20");
  @source inline("data-[focus-visible]:ring-inset");
  @source inline("data-[focus-visible]:ring-offset-2");
  @source inline("data-[focus-visible]:ring-offset-background");
  @source inline("data-[focus-visible]:ring-ring/40");
  @source inline("data-[focus-visible]:ring-ring/50");
  @source inline("data-[focus-visible]:shadow-xs");
  @source inline("data-[focus-visible]:text-foreground");
  @source inline("duration-200");
  @source inline("ease-in-out");
  @source inline("flex");
  @source inline("flex-col");
  @source inline("font-medium");
  @source inline("gap-1");
  @source inline("gap-1.5");
  @source inline("gap-2");
  @source inline("gap-3");
  @source inline("group/button");
  @source inline("h-10");
  @source inline("h-6");
  @source inline("h-7");
  @source inline("h-8");
  @source inline("h-9");
  @source inline("hidden");
  @source inline("hover:aria-checked:bg-input");
  @source inline("hover:aria-checked:bg-muted/60");
  @source inline("hover:aria-checked:bg-primary/90");
  @source inline("hover:aria-checked:text-foreground");
  @source inline("hover:aria-selected:bg-background/70");
  @source inline("hover:aria-selected:shadow-xs");
  @source inline("hover:aria-selected:text-foreground");
  @source inline("hover:bg-destructive/20");
  @source inline("hover:bg-muted");
  @source inline("hover:bg-primary/80");
  @source inline("hover:bg-secondary/80");
  @source inline("hover:data-[focus-visible]:data-[focused]:bg-muted");
  @source inline("hover:data-[focus-visible]:data-[focused]:text-foreground");
  @source inline("hover:text-foreground");
  @source inline("hover:underline");
  @source inline("inline-flex");
  @source inline("items-center");
  @source inline("items-start");
  @source inline("justify-center");
  @source inline("leading-6");
  @source inline("left-0");
  @source inline("min-h-28");
  @source inline("min-w-10");
  @source inline("min-w-56");
  @source inline("min-w-8");
  @source inline("min-w-9");
  @source inline("mt-2");
  @source inline("opacity-50");
  @source inline("outline-none");
  @source inline("overflow-hidden");
  @source inline("p-1");
  @source inline("p-4");
  @source inline("peer");
  @source inline("pl-0.5");
  @source inline("pl-[22px]");
  @source inline("pointer-events-none");
  @source inline("pr-0.5");
  @source inline("pr-[22px]");
  @source inline("px-2.5");
  @source inline("px-3");
  @source inline("px-5");
  @source inline("py-1.5");
  @source inline("py-2");
  @source inline("relative");
  @source inline("ring-0");
  @source inline("ring-2");
  @source inline("ring-3");
  @source inline("ring-destructive/20");
  @source inline("ring-destructive/40");
  @source inline("ring-inset");
  @source inline("ring-offset-2");
  @source inline("ring-offset-background");
  @source inline("ring-ring/40");
  @source inline("ring-ring/50");
  @source inline("rounded-[min(var(--radius-md),12px)]");
  @source inline("rounded-full");
  @source inline("rounded-lg");
  @source inline("rounded-md");
  @source inline("rounded-xl");
  @source inline("scale-[0.98]");
  @source inline("scale-[0.99]");
  @source inline("select-none");
  @source inline("shadow-lg");
  @source inline("shadow-xs");
  @source inline("shrink-0");
  @source inline("size-5");
  @source inline("size-8");
  @source inline("text-[0.8rem]");
  @source inline("text-accent-foreground");
  @source inline("text-destructive");
  @source inline("text-foreground");
  @source inline("text-left");
  @source inline("text-muted-foreground");
  @source inline("text-primary");
  @source inline("text-primary-foreground");
  @source inline("text-secondary-foreground");
  @source inline("text-sm");
  @source inline("top-full");
  @source inline("transition-all");
  @source inline("transition-colors");
  @source inline("translate-x-0");
  @source inline("translate-y-px");
  @source inline("underline");
  @source inline("underline-offset-4");
  @source inline("w-11");
  @source inline("w-80");
  @source inline("w-full");
  @source inline("whitespace-nowrap");
  @source inline("will-change-transform");
  @source inline("z-50");
  `;

export const SHADCN_THEME_CSS = `:root {
    --radius: 0.625rem;
    --background: lab(100% 0 0);
    --foreground: lab(2.75381% 0 0);
    --card: lab(100% 0 0);
    --card-foreground: lab(2.75381% 0 0);
    --popover: lab(100% 0 0);
    --popover-foreground: lab(2.75381% 0 0);
    --primary: lab(7.78201% -0.0000149012 0);
    --primary-foreground: lab(98.26% 0 0);
    --secondary: lab(96.52% -0.0000298023 0.0000119209);
    --secondary-foreground: lab(7.78201% -0.0000149012 0);
    --muted: lab(96.52% -0.0000298023 0.0000119209);
    --muted-foreground: lab(48.496% 0 0);
    --accent: lab(96.52% -0.0000298023 0.0000119209);
    --accent-foreground: lab(7.78201% -0.0000149012 0);
    --destructive: lab(48.4493% 77.4328 61.5452);
    --destructive-foreground: lab(96.4152% 3.22586 1.14673);
    --border: lab(90.952% 0 -0.0000119209);
    --input: lab(90.952% 0 -0.0000119209);
    --ring: lab(66.128% -0.0000298023 0.0000119209);
    --chart-1: var(--color-blue-300);
    --chart-2: var(--color-blue-500);
    --chart-3: var(--color-blue-600);
    --chart-4: var(--color-blue-700);
    --chart-5: var(--color-blue-800);
    --sidebar: lab(98.26% 0 0);
    --sidebar-foreground: lab(2.75381% 0 0);
    --sidebar-primary: lab(7.78201% -0.0000149012 0);
    --sidebar-primary-foreground: lab(98.26% 0 0);
    --sidebar-accent: lab(96.52% -0.0000298023 0.0000119209);
    --sidebar-accent-foreground: lab(7.78201% -0.0000149012 0);
    --sidebar-border: lab(90.952% 0 -0.0000119209);
    --sidebar-ring: lab(66.128% -0.0000298023 0.0000119209);
    --surface: lab(97.68% -0.0000298023 0.0000119209);
    --surface-foreground: var(--foreground);
    --code: var(--surface);
    --code-foreground: var(--surface-foreground);
    --code-highlight: lab(95.36% 0 0);
    --code-number: lab(48.96% 0 0);
    --selection: lab(2.75381% 0 0);
    --selection-foreground: lab(100% 0 0);
  }
  
  :root.dark,
  :root[data-theme='dark'] {
    --background: lab(2.75381% 0 0);
    --foreground: lab(98.26% 0 0);
    --card: lab(7.78201% -0.0000149012 0);
    --card-foreground: lab(98.26% 0 0);
    --popover: lab(7.78201% -0.0000149012 0);
    --popover-foreground: lab(98.26% 0 0);
    --primary: lab(90.952% 0 -0.0000119209);
    --primary-foreground: lab(7.78201% -0.0000149012 0);
    --secondary: lab(15.204% 0 -0.00000596046);
    --secondary-foreground: lab(98.26% 0 0);
    --muted: lab(15.204% 0 -0.00000596046);
    --muted-foreground: lab(66.128% -0.0000298023 0.0000119209);
    --accent: lab(27.036% 0 0);
    --accent-foreground: lab(98.26% 0 0);
    --destructive: lab(63.7053% 60.745 31.3109);
    --destructive-foreground: lab(49.0747% 69.3434 49.6251);
    --border: lab(100% 0 0 / 0.1);
    --input: lab(100% 0 0 / 0.15);
    --ring: lab(48.496% 0 0);
    --chart-1: var(--color-blue-300);
    --chart-2: var(--color-blue-500);
    --chart-3: var(--color-blue-600);
    --chart-4: var(--color-blue-700);
    --chart-5: var(--color-blue-800);
    --sidebar: lab(7.78201% -0.0000149012 0);
    --sidebar-foreground: lab(98.26% 0 0);
    --sidebar-primary: lab(36.9089% 35.0961 -85.6872);
    --sidebar-primary-foreground: lab(98.26% 0 0);
    --sidebar-accent: lab(15.204% 0 -0.00000596046);
    --sidebar-accent-foreground: lab(98.26% 0 0);
    --sidebar-border: lab(100% 0 0 / 0.1);
    --sidebar-ring: lab(34.924% 0 0);
    --surface: lab(7.22637% -0.0000149012 0);
    --surface-foreground: lab(66.128% -0.0000298023 0.0000119209);
    --code: var(--surface);
    --code-foreground: var(--surface-foreground);
    --code-highlight: lab(15.32% 0 0);
    --code-number: lab(67.52% -0.0000298023 0);
    --selection: lab(90.952% 0 -0.0000119209);
    --selection-foreground: lab(7.78201% -0.0000149012 0);
  }
  `;

export const TAILWIND_BASE_TEMPLATE = `@import 'tailwindcss'; 
  @import '__THEME_IMPORT__';
  @import '__TOKENS_IMPORT__';
  
  @custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));
  
  @theme {
    --radius: 0.625rem;
    --radius-xl: calc(var(--radius) + 4px);
    --radius-lg: var(--radius);
    --radius-md: calc(var(--radius) - 2px);
    --radius-sm: calc(var(--radius) - 4px);
    --color-background: var(--background);
    --color-foreground: var(--foreground);
    --color-card: var(--card);
    --color-card-foreground: var(--card-foreground);
    --color-popover: var(--popover);
    --color-popover-foreground: var(--popover-foreground);
    --color-primary: var(--primary);
    --color-primary-foreground: var(--primary-foreground);
    --color-secondary: var(--secondary);
    --color-secondary-foreground: var(--secondary-foreground);
    --color-muted: var(--muted);
    --color-muted-foreground: var(--muted-foreground);
    --color-accent: var(--accent);
    --color-accent-foreground: var(--accent-foreground);
    --color-destructive: var(--destructive);
    --color-destructive-foreground: var(--destructive-foreground);
    --color-border: var(--border);
    --color-input: var(--input);
    --color-ring: var(--ring);
    --color-chart-1: var(--chart-1);
    --color-chart-2: var(--chart-2);
    --color-chart-3: var(--chart-3);
    --color-chart-4: var(--chart-4);
    --color-chart-5: var(--chart-5);
    --color-sidebar: var(--sidebar);
    --color-sidebar-foreground: var(--sidebar-foreground);
    --color-sidebar-primary: var(--sidebar-primary);
    --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
    --color-sidebar-accent: var(--sidebar-accent);
    --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
    --color-sidebar-border: var(--sidebar-border);
    --color-sidebar-ring: var(--sidebar-ring);
    --color-surface: var(--surface);
    --color-surface-foreground: var(--surface-foreground);
    --color-code: var(--code);
    --color-code-foreground: var(--code-foreground);
    --color-code-highlight: var(--code-highlight);
    --color-code-number: var(--code-number);
    --color-selection: var(--selection);
    --color-selection-foreground: var(--selection-foreground);
  }
  
  @font-face {
    font-family: 'GeistSans';
    src: url('./assets/font/GeistVF.woff2') format('woff2-variations');
  }
  
  @layer base {
    :root {
      --radius-xl: calc(var(--radius) + 4px);
      --radius-lg: var(--radius);
      --radius-md: calc(var(--radius) - 2px);
      --radius-sm: calc(var(--radius) - 4px);
    }
  
    * {
      border-color: var(--color-border);
    }
  }
  
  body {
    background-color: var(--color-background);
    color: var(--color-foreground);
    font-family:
      var(--color-font-geist-sans),
      ui-sans-serif,
      system-ui,
      -apple-system,
      BlinkMacSystemFont,
      'Segoe UI',
      Roboto,
      'Helvetica Neue',
      Arial,
      'Noto Sans',
      sans-serif,
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'Noto Color Emoji';
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    unicode-bidi: isolate;
    font-feature-settings: normal;
    font-synthesis-weight: none;
    font-variation-settings: normal;
    text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }
  `;
